app = "goshen112-back-up1234"

[build]
  dockerfile = "Dockerfile"

[mounts]
  source = "data"
  destination = "/var/www/database/sqlite"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
